### ISSUE TITLE
ALIGN ON SCHEMA

### ISSUE THREAD

**Issue by kdduan** [software-students-fall2021/project-setup-penguin#130]
Our code still has conflicting representations of the users schema. 
* userId / email / username inconsistencies: some endpoints or FE logic treat refer to the user's email as `email` or `username`, sometimes we treat `email` equivalent to a userId and sometimes we expect a `userId` field. 
* cards / decks inconsistencies: some endpoints expect a user to have a value for both `cards` and `decks` while other pieces of logic only expect the user to have a `cards` field and expect to the decks by accessing the `deckId` variable for each `card` object. 

Need to align on the above issues before we integrate with Mongo and establish our schema there. 

Proposed Schemas: 
Decks
```
deckId: {
  deckId: string,
  joinCode: string,
  ownerId: string,
  deckName: string,
  deckDescription: string,
  cardTemplate: {
    name: string,
    city: string,
    tagline: string,
    summary: string,
    sectionLabel0: string,
    sectionLabel1: string,
    sectionLabel2: string,
    sectionContent0: string,
    sectionContent1: string,
    sectionContent2: string,
    sliderLabelMin: string,
    sliderLabelMax: string,
    sliderValue: int,
    image: string
  },
  cards: [
    "cardId1",
    "cardId2"
  ]
}
```
Cards
```
cardId: {
  cardId: string,
  deckId: string,
  userId: string, 
  imageId: string,
  name: string,
  city: string,
  tagline: string,
  summary: string,
  sectionContent0: string,
  sectionContent1: string,
  sectionContent2: string,
  sliderValue: int
}
```
Users
```
userId: {
  userId: string,
  name: string,
  email: string,
  password: string (hashed),
  cards: [ (we're not storing an array for deckIds since each cardId is mapped 1:1 to a deckId - allows us to save on the data we need to manage)
    cardId1,
    cardId2
  ]
}
```

**Comment by janethuangg** [comment]
note: the `cards` field in User schema got renamed to `card`, which is breaking some things
