### ISSUE TITLE
As a team leader, I want to create a custom card / template for my team, so that we have more flexibility

### ISSUE THREAD

**Issue by kdduan** [software-students-fall2021/project-setup-penguin#15]
## Estimation of work
- TBD

## Acceptance criteria
- [ ] user can update card labels
- [ ] user can update placeholder text
- [ ] template is shown to new team members upon card creation

**Comment by janethuangg** [comment]
collapsed into https://github.com/software-students-fall2021/project-setup-penguin/issues/13
